### ISSUE TITLE
`require': cannot load such file -- ubygems (LoadError)

### ISSUE THREAD

**Issue by skatkov** [seattlerb/zentest#73]
After ruby update my favorite `autotest` feature stopped working, with a following error:

```
$ autotest
/Users/sk/.rvm/rubies/ruby-2.6.3/bin/ruby -I.:lib:test -rubygems -e "gem 'minitest'; %w[minitest/autorun test/jobs/product_update_job_test.rb test/services/product_add_parent_test.rb test/controllers/storefront/feed_controller_test.rb test/system/storefronts_test.rb test/lib/parsers/item_test.rb test/services/similar_products_query_test.rb test/services/amazon_lookup_test.rb test/helpers/storefront_helper_test.rb test/models/client_test.rb test/controllers/product_categories_controller_test.rb test/controllers/home_controller_test.rb test/helpers/application_helper_test.rb test/forms/settings_form_test.rb test/forms/category_form_test.rb test/controllers/store_selector_test.rb test/lib/amazon_order_validator_test.rb test/controllers/storefront/products_controller_test.rb test/controllers/categories_controller_test.rb test/controllers/clients_controller_test.rb test/presenters/product_variation_presenter_test.rb test/test_helper.rb test/controllers/domains_test.rb test/models/service_message_test.rb test/forms/new_store_form_test.rb test/controllers/api/cart_controller_test.rb test/forms/new_client_form_test.rb test/controllers/callbacks_controller_test.rb test/jobs/heroku_domain_job_test.rb test/forms/category_add_products_test.rb test/models/order_test.rb test/controllers/stores_controller_test.rb test/forms/search_form_test.rb test/lib/parsers/variations_test.rb test/services/category_remove_test.rb test/services/order_service_test.rb test/presenters/products_grid_presenter_test.rb test/lib/product_advertising_test.rb test/services/search_service_test.rb test/models/store_test.rb test/services/product_add_test.rb test/services/product_update_test.rb test/jobs/store_update_job_test.rb test/models/product_test.rb test/lib/parsers/data_test.rb test/controllers/search_controller_test.rb test/views/storefront_test.rb test/services/products_without_category_query_test.rb test/system/landing_test.rb test/serializers/product_lookup_serializer_test.rb test/controllers/storefront/categories_controller_test.rb test/controllers/products_controller_test.rb test/models/product_variation_test.rb test/serializers/merchant_feed_serializer_test.rb test/controllers/storefront_controller_test.rb].each { |f| require f }" -- --server 30119
Traceback (most recent call last):
	1: from /Users/sk/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/sk/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ubygems (LoadError)
```

I've noticed similar issue in minitest-autotest gem https://github.com/seattlerb/minitest-autotest/pull/14

But it seems that autotest iteself contains similar code:

https://github.com/seattlerb/zentest/blob/bb29cd8c81b245d2a73053595f290e28a571f378/lib/autotest.rb#L731

# Workaround
I downgraded ruby to 2.5.* version and it worked.

# My environment:
```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
```

Gemfile
```
GIT
  remote: https://github.com/thepracticaldev/fix-db-schema-conflicts.git
  revision: 4172392392e1a8d907f7ab673cb5ddd9a4a31940
  branch: master
  specs:
    fix-db-schema-conflicts (3.0.2)
      rubocop (>= 0.38.0)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.3)
      actionpack (= 5.2.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.3)
      actionview (= 5.2.3)
      activesupport (= 5.2.3)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.3)
      activesupport (= 5.2.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.3)
      activesupport (= 5.2.3)
      globalid (>= 0.3.6)
    activemodel (5.2.3)
      activesupport (= 5.2.3)
    activerecord (5.2.3)
      activemodel (= 5.2.3)
      activesupport (= 5.2.3)
      arel (>= 9.0)
    activestorage (5.2.3)
      actionpack (= 5.2.3)
      activerecord (= 5.2.3)
      marcel (~> 0.3.1)
    activesupport (5.2.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    acts-as-taggable-array-on (0.5.1)
      activerecord (>= 4)
      activesupport (>= 4)
    addressable (2.6.0)
      public_suffix (>= 2.0.2, < 4.0)
    ansi (1.5.0)
    arel (9.0.0)
    ast (2.4.0)
    bcrypt (3.1.12)
    bindex (0.7.0)
    builder (3.2.3)
    bulma-extensions-rails (1.0.30)
    bulma-rails (0.7.4)
      sass (~> 3.5)
    bulmajs-rails (0.3.3)
    byebug (11.0.1)
    capybara (3.17.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.2)
      xpath (~> 3.2)
    childprocess (1.0.1)
      rake (< 13.0)
    cliver (0.3.2)
    coderay (1.1.2)
    concurrent-ruby (1.1.5)
    connection_pool (2.2.2)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    crass (1.0.4)
    curb (0.9.10)
    devise (4.6.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    discard (1.0.0)
      activerecord (>= 4.2, < 6)
    dotenv (2.7.2)
    dotenv-rails (2.7.2)
      dotenv (= 2.7.2)
      railties (>= 3.2, < 6.1)
    erubi (1.8.0)
    erubis (2.7.0)
    excon (0.64.0)
    execjs (2.7.0)
    ffi (1.10.0)
    flamegraph (0.9.5)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    hashdiff (0.3.8)
    hashie (3.6.0)
    heroics (0.0.25)
      erubis (~> 2.0)
      excon
      moneta
      multi_json (>= 1.9.2)
    heroku-deflater (0.6.3)
      rack (>= 1.4.5)
    high_voltage (3.1.0)
    honeybadger (4.2.1)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    jaro_winkler (1.5.2)
    jeff (2.0.0)
      excon (>= 0.22.1)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.7.0)
      launchy (~> 2.2)
    libv8 (3.16.14.19)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    marginalia (1.8.0)
      actionpack (>= 2.3)
      activerecord (>= 2.3)
    memory_profiler (0.9.13)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.1)
    mini_portile2 (2.4.0)
    minispec-metadata (2.0.0)
      minitest
    minitest (5.11.3)
    minitest-autotest (1.0.3)
      minitest-server (~> 1.0)
    minitest-reporters (1.3.6)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    minitest-server (1.0.5)
      minitest (~> 5.0)
    minitest-vcr (1.4.0)
      minispec-metadata (~> 2.0)
      minitest (>= 4.7.5)
      vcr (>= 2.9)
    moneta (1.0.0)
    multi_json (1.13.1)
    multi_xml (0.6.0)
    mustermann (1.0.3)
    nanoid (2.0.0)
    nio4r (2.3.1)
    nokogiri (1.10.2)
      mini_portile2 (~> 2.4.0)
    orm_adapter (0.5.0)
    parallel (1.17.0)
    parser (2.6.2.1)
      ast (~> 2.4.0)
    pg (1.1.4)
    pgrel (0.3.0)
      activerecord (>= 4.0)
    platform-api (2.2.0)
      heroics (~> 0.0.25)
      moneta (~> 1.0.0)
    poltergeist (1.18.1)
      capybara (>= 2.1, < 4)
      cliver (~> 0.3.1)
      websocket-driver (>= 0.2.0)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.7.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    psych (3.1.0)
    public_suffix (3.0.3)
    puma (3.12.1)
    rack (2.0.7)
    rack-attack (6.0.0)
      rack (>= 1.0, < 3)
    rack-cors (1.0.3)
    rack-mini-profiler (1.0.2)
      rack (>= 1.2.0)
    rack-protection (2.0.5)
      rack
    rack-proxy (0.6.5)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.3)
      actioncable (= 5.2.3)
      actionmailer (= 5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      activemodel (= 5.2.3)
      activerecord (= 5.2.3)
      activestorage (= 5.2.3)
      activesupport (= 5.2.3)
      bundler (>= 1.3.0)
      railties (= 5.2.3)
      sprockets-rails (>= 2.0.0)
    rails-controller-testing (1.0.4)
      actionpack (>= 5.0.1.x)
      actionview (>= 5.0.1.x)
      activesupport (>= 5.0.1.x)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.2.3)
      actionpack (= 5.2.3)
      activesupport (= 5.2.3)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rainbow (3.0.0)
    rake (12.3.2)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    redis (4.1.0)
    ref (2.0.0)
    regexp_parser (1.4.0)
    responders (2.4.1)
      actionpack (>= 4.2.0, < 6.0)
      railties (>= 4.2.0, < 6.0)
    rubocop (0.67.2)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      psych (>= 3.1.0)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 1.6)
    ruby-progressbar (1.10.0)
    ruby_dep (1.5.0)
    ruby_http_client (3.3.0)
    rubyzip (1.2.2)
    safe_yaml (1.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    selenium-webdriver (3.141.5926)
      childprocess (>= 0.5, < 2.0)
      rubyzip (~> 1.2, >= 1.2.2)
    sendgrid-ruby (5.3.0)
      ruby_http_client (~> 3.3.0)
      sinatra (>= 1.4.7, < 3)
    sidekiq (5.2.6)
      connection_pool (~> 2.2, >= 2.2.2)
      rack (>= 1.5.0)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sinatra (2.0.5)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.5)
      tilt (~> 2.0)
    single_test (0.6.0)
      rake
    snake_case_hash (1.0.4)
      hashie (~> 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    stackprof (0.2.12)
    strong_migrations (0.3.1)
      activerecord (>= 3.2.0)
    terminal-notifier (2.0.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.9)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.20)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.5.0)
    vacuum (2.1.1)
      jeff (~> 2.0)
      multi_xml (~> 0.6.0)
    vcr (4.0.0)
    warden (1.2.8)
      rack (>= 2.0.6)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    webmock (3.5.1)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    webpacker (4.0.2)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    websocket-driver (0.7.0)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    yard (0.9.19)

PLATFORMS
  ruby

DEPENDENCIES
  acts-as-taggable-array-on
  builder (~> 3.2)
  bulma-extensions-rails
  bulma-rails
  bulmajs-rails
  byebug
  capybara
  curb
  devise
  discard
  dotenv-rails
  fix-db-schema-conflicts!
  flamegraph
  heroku-deflater
  high_voltage
  honeybadger
  letter_opener
  listen (>= 3.0.5, < 3.2)
  marginalia
  memory_profiler
  minitest
  minitest-autotest
  minitest-reporters
  minitest-vcr
  nanoid
  pg
  pgrel (~> 0.2)
  platform-api
  poltergeist
  pry-byebug
  pry-rails
  puma (~> 3.7)
  rack-attack
  rack-cors
  rack-mini-profiler
  rails (~> 5.2)
  rails-controller-testing
  redis
  rubocop
  selenium-webdriver
  sendgrid-ruby
  sidekiq
  single_test
  snake_case_hash
  stackprof
  strong_migrations
  terminal-notifier
  therubyracer
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  vacuum
  web-console (>= 3.3.0)
  webmock
  webpacker
  yard

RUBY VERSION
   ruby 2.6.3p62

BUNDLED WITH
   1.17.3

```

**Comment by zenspider** [comment]
This is definitely fixed (and released? I'm pretty sure) over in `minitest-autotest` and is the right thing to run. I didn't even notice that `autotest.rb` was still in ZenTest. I will fix this issue by removing it entirely.

Thank you for the report.

**Comment by skatkov** [comment]
Great @zenspider 

I added a workaround section to original post, just in case somebody else will be looking for one.

**Comment by zenspider** [comment]
Done. Thank you.
